// home
export const HOMESAVEFORMDATA = 'HOMESAVEFORMDATA'
export const HOMESAVEIMG = 'HOMESAVEIMG'
export const HOMECLEARDATA = 'HOMECLEARDATA'

// production
export const PROGETPRODUCTION = 'PROGETPRODUCTION'
export const PROTOGGLESELECT = 'PROTOGGLESELECT'
export const PROEDITPRODUCTION = 'PROEDITPRODUCTION'
export const PROCLEARSELECTED = 'PROCLEARSELECTED'